# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a851aaab351447ae3958d04dc1b7d67601b68120cb38e88e855ecc01a83a700d2cd94da23b9a5beaa1878e25b68b1a3da9e3c960e735efd621d87f23471b6e58

test:
  secret_key_base: d89504e8d9a0360322ddf00a88bd46e7f8b981ff1eece08855d7d9150ed8354a558f5b75cd08a0b407a9bf9ff49056c4fdcdc966c4d2821e27842002f328cf69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
